### PR TITLE
add protostar deployment scripts for local-devnet, testnet, testnet2

### PR DESCRIPTION
**Pull request by cryptoleek-eth**
- Added protostar deployment scripts for local-devnet, testnet, testnet2
- Updated readme file.
- Added protostar config file
- Updated file stcutures for protostar

### CODE REVIEW

**Review by l-henri — COMMENTED** [review]
The table and addresses of the testnet 2 are missing

**Review by l-henri — CHANGES_REQUESTED** [review]
The table and addresses of the testnet 2 are missing in the readme, can you add them please?

Non blocking:
Regarding files deploy/protostar_deploy_testnet2.md deploy/protostar_deploy_testnet.md and deploy/protostar_deploy_local.md
is it possible to write the deployments as a set of scripts that can be run with a single command?

**Comment by l-henri** [comment]
Extra request, can you add instructions to set up protostar in the readme, to make protostar the default tool when using this tutorial?
- Add instructions to set up protostar
- Modify the commands we recommend running (eg starknet-compile) to use protostar by default

**Comment by vinseabook** [comment]
@omarespejel @l-henri I updated the scripts and readme and please have a second look

**Comment by omarespejel** [comment]
Hey @vinseabook! Maybe we should close this PR and do something similar with Scarb once it is ready?

**Comment by barretodavid** [comment]
@cryptoleek-eth with the release of Cairo 1, is this PR still valid in your opinion?

**Comment by cryptoleek-eth** [comment]
we need to update the PR. Currently is not valid.

**Comment by cryptoleek-eth** [comment]
I will close it for now.

**Pull request closed without merging**
